//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aluminum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Costume
    {
        public short CostumeID { get; set; }
        public string Name { get; set; }
        public string ImageFileName { get; set; }
        public Nullable<GenderType> GenderTypeID { get; set; }
        public bool IsFictional { get; set; }
        public bool IsHuman { get; set; }
        public bool HasSuperPowers { get; set; }
        public bool HasFacialHair { get; set; }
        public bool HasMagic { get; set; }
    }
}
