#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aluminum.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_9BB309_GiantChocobo")]
	public partial class RoomOfRequirementDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCostumeQuestion(CostumeQuestion instance);
    partial void UpdateCostumeQuestion(CostumeQuestion instance);
    partial void DeleteCostumeQuestion(CostumeQuestion instance);
    partial void InsertCostume(Costume instance);
    partial void UpdateCostume(Costume instance);
    partial void DeleteCostume(Costume instance);
    #endregion
		
		public RoomOfRequirementDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB_9BB309_GiantChocoboConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public RoomOfRequirementDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RoomOfRequirementDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RoomOfRequirementDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RoomOfRequirementDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CostumeQuestion> CostumeQuestions
		{
			get
			{
				return this.GetTable<CostumeQuestion>();
			}
		}
		
		public System.Data.Linq.Table<Costume> Costumes
		{
			get
			{
				return this.GetTable<Costume>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CostumeQuestion")]
	public partial class CostumeQuestion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Question;
		
		private string _Answered;
		
		private string _DataField;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnQuestionChanging(string value);
    partial void OnQuestionChanged();
    partial void OnAnsweredChanging(string value);
    partial void OnAnsweredChanged();
    partial void OnDataFieldChanging(string value);
    partial void OnDataFieldChanged();
    #endregion
		
		public CostumeQuestion()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Question", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Question
		{
			get
			{
				return this._Question;
			}
			set
			{
				if ((this._Question != value))
				{
					this.OnQuestionChanging(value);
					this.SendPropertyChanging();
					this._Question = value;
					this.SendPropertyChanged("Question");
					this.OnQuestionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Answered", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Answered
		{
			get
			{
				return this._Answered;
			}
			set
			{
				if ((this._Answered != value))
				{
					this.OnAnsweredChanging(value);
					this.SendPropertyChanging();
					this._Answered = value;
					this.SendPropertyChanged("Answered");
					this.OnAnsweredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataField", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string DataField
		{
			get
			{
				return this._DataField;
			}
			set
			{
				if ((this._DataField != value))
				{
					this.OnDataFieldChanging(value);
					this.SendPropertyChanging();
					this._DataField = value;
					this.SendPropertyChanged("DataField");
					this.OnDataFieldChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Costume")]
	public partial class Costume : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _CostumeID;
		
		private string _Name;
		
		private string _ImageFileName;
		
		private System.Nullable<byte> _GenderTypeID;
		
		private bool _IsFictional;
		
		private bool _IsHuman;
		
		private bool _HasSuperPowers;
		
		private bool _HasFacialHair;
		
		private bool _HasMagic;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCostumeIDChanging(short value);
    partial void OnCostumeIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnImageFileNameChanging(string value);
    partial void OnImageFileNameChanged();
    partial void OnGenderTypeIDChanging(System.Nullable<byte> value);
    partial void OnGenderTypeIDChanged();
    partial void OnIsFictionalChanging(bool value);
    partial void OnIsFictionalChanged();
    partial void OnIsHumanChanging(bool value);
    partial void OnIsHumanChanged();
    partial void OnHasSuperPowersChanging(bool value);
    partial void OnHasSuperPowersChanged();
    partial void OnHasFacialHairChanging(bool value);
    partial void OnHasFacialHairChanged();
    partial void OnHasMagicChanging(bool value);
    partial void OnHasMagicChanged();
    #endregion
		
		public Costume()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostumeID", AutoSync=AutoSync.OnInsert, DbType="SmallInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public short CostumeID
		{
			get
			{
				return this._CostumeID;
			}
			set
			{
				if ((this._CostumeID != value))
				{
					this.OnCostumeIDChanging(value);
					this.SendPropertyChanging();
					this._CostumeID = value;
					this.SendPropertyChanged("CostumeID");
					this.OnCostumeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageFileName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ImageFileName
		{
			get
			{
				return this._ImageFileName;
			}
			set
			{
				if ((this._ImageFileName != value))
				{
					this.OnImageFileNameChanging(value);
					this.SendPropertyChanging();
					this._ImageFileName = value;
					this.SendPropertyChanged("ImageFileName");
					this.OnImageFileNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GenderTypeID", DbType="TinyInt")]
		public System.Nullable<byte> GenderTypeID
		{
			get
			{
				return this._GenderTypeID;
			}
			set
			{
				if ((this._GenderTypeID != value))
				{
					this.OnGenderTypeIDChanging(value);
					this.SendPropertyChanging();
					this._GenderTypeID = value;
					this.SendPropertyChanged("GenderTypeID");
					this.OnGenderTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsFictional", DbType="Bit NOT NULL")]
		public bool IsFictional
		{
			get
			{
				return this._IsFictional;
			}
			set
			{
				if ((this._IsFictional != value))
				{
					this.OnIsFictionalChanging(value);
					this.SendPropertyChanging();
					this._IsFictional = value;
					this.SendPropertyChanged("IsFictional");
					this.OnIsFictionalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsHuman", DbType="Bit NOT NULL")]
		public bool IsHuman
		{
			get
			{
				return this._IsHuman;
			}
			set
			{
				if ((this._IsHuman != value))
				{
					this.OnIsHumanChanging(value);
					this.SendPropertyChanging();
					this._IsHuman = value;
					this.SendPropertyChanged("IsHuman");
					this.OnIsHumanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasSuperPowers", DbType="Bit NOT NULL")]
		public bool HasSuperPowers
		{
			get
			{
				return this._HasSuperPowers;
			}
			set
			{
				if ((this._HasSuperPowers != value))
				{
					this.OnHasSuperPowersChanging(value);
					this.SendPropertyChanging();
					this._HasSuperPowers = value;
					this.SendPropertyChanged("HasSuperPowers");
					this.OnHasSuperPowersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasFacialHair", DbType="Bit NOT NULL")]
		public bool HasFacialHair
		{
			get
			{
				return this._HasFacialHair;
			}
			set
			{
				if ((this._HasFacialHair != value))
				{
					this.OnHasFacialHairChanging(value);
					this.SendPropertyChanging();
					this._HasFacialHair = value;
					this.SendPropertyChanged("HasFacialHair");
					this.OnHasFacialHairChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasMagic", DbType="Bit NOT NULL")]
		public bool HasMagic
		{
			get
			{
				return this._HasMagic;
			}
			set
			{
				if ((this._HasMagic != value))
				{
					this.OnHasMagicChanging(value);
					this.SendPropertyChanging();
					this._HasMagic = value;
					this.SendPropertyChanged("HasMagic");
					this.OnHasMagicChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
