#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aluminum.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_9BB309_GiantChocobo")]
	public partial class RoomOfRequirementDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCostume(Costume instance);
    partial void UpdateCostume(Costume instance);
    partial void DeleteCostume(Costume instance);
    #endregion
		
		public RoomOfRequirementDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB_9BB309_GiantChocoboConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public RoomOfRequirementDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RoomOfRequirementDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RoomOfRequirementDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RoomOfRequirementDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Costume> Costumes
		{
			get
			{
				return this.GetTable<Costume>();
			}
		}
		
		public System.Data.Linq.Table<CostumeQuestion> CostumeQuestions
		{
			get
			{
				return this.GetTable<CostumeQuestion>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Costume")]
	public partial class Costume : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _CostumeID;
		
		private string _Name;
		
		private string _ImageFileName;
		
		private byte _GenderTypeID;
		
		private bool _IsHuman;
		
		private bool _IsHumanoid;
		
		private bool _IsAnimal;
		
		private bool _IsAlien;
		
		private bool _IsThing;
		
		private bool _HasSuperPowers;
		
		private bool _HasPants;
		
		private bool _HasShirt;
		
		private bool _HasShoes;
		
		private bool _HasBoots;
		
		private bool _HasHat;
		
		private bool _HasCape;
		
		private bool _HasScarf;
		
		private bool _HasDyedHair;
		
		private bool _HasFacialHair;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCostumeIDChanging(short value);
    partial void OnCostumeIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnImageFileNameChanging(string value);
    partial void OnImageFileNameChanged();
    partial void OnGenderTypeIDChanging(byte value);
    partial void OnGenderTypeIDChanged();
    partial void OnIsHumanChanging(bool value);
    partial void OnIsHumanChanged();
    partial void OnIsHumanoidChanging(bool value);
    partial void OnIsHumanoidChanged();
    partial void OnIsAnimalChanging(bool value);
    partial void OnIsAnimalChanged();
    partial void OnIsAlienChanging(bool value);
    partial void OnIsAlienChanged();
    partial void OnIsThingChanging(bool value);
    partial void OnIsThingChanged();
    partial void OnHasSuperPowersChanging(bool value);
    partial void OnHasSuperPowersChanged();
    partial void OnHasPantsChanging(bool value);
    partial void OnHasPantsChanged();
    partial void OnHasShirtChanging(bool value);
    partial void OnHasShirtChanged();
    partial void OnHasShoesChanging(bool value);
    partial void OnHasShoesChanged();
    partial void OnHasBootsChanging(bool value);
    partial void OnHasBootsChanged();
    partial void OnHasHatChanging(bool value);
    partial void OnHasHatChanged();
    partial void OnHasCapeChanging(bool value);
    partial void OnHasCapeChanged();
    partial void OnHasScarfChanging(bool value);
    partial void OnHasScarfChanged();
    partial void OnHasDyedHairChanging(bool value);
    partial void OnHasDyedHairChanged();
    partial void OnHasFacialHairChanging(bool value);
    partial void OnHasFacialHairChanged();
    #endregion
		
		public Costume()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostumeID", AutoSync=AutoSync.OnInsert, DbType="SmallInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public short CostumeID
		{
			get
			{
				return this._CostumeID;
			}
			set
			{
				if ((this._CostumeID != value))
				{
					this.OnCostumeIDChanging(value);
					this.SendPropertyChanging();
					this._CostumeID = value;
					this.SendPropertyChanged("CostumeID");
					this.OnCostumeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageFileName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ImageFileName
		{
			get
			{
				return this._ImageFileName;
			}
			set
			{
				if ((this._ImageFileName != value))
				{
					this.OnImageFileNameChanging(value);
					this.SendPropertyChanging();
					this._ImageFileName = value;
					this.SendPropertyChanged("ImageFileName");
					this.OnImageFileNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GenderTypeID", DbType="TinyInt NOT NULL")]
		public byte GenderTypeID
		{
			get
			{
				return this._GenderTypeID;
			}
			set
			{
				if ((this._GenderTypeID != value))
				{
					this.OnGenderTypeIDChanging(value);
					this.SendPropertyChanging();
					this._GenderTypeID = value;
					this.SendPropertyChanged("GenderTypeID");
					this.OnGenderTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsHuman", DbType="Bit NOT NULL")]
		public bool IsHuman
		{
			get
			{
				return this._IsHuman;
			}
			set
			{
				if ((this._IsHuman != value))
				{
					this.OnIsHumanChanging(value);
					this.SendPropertyChanging();
					this._IsHuman = value;
					this.SendPropertyChanged("IsHuman");
					this.OnIsHumanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsHumanoid", DbType="Bit NOT NULL")]
		public bool IsHumanoid
		{
			get
			{
				return this._IsHumanoid;
			}
			set
			{
				if ((this._IsHumanoid != value))
				{
					this.OnIsHumanoidChanging(value);
					this.SendPropertyChanging();
					this._IsHumanoid = value;
					this.SendPropertyChanged("IsHumanoid");
					this.OnIsHumanoidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAnimal", DbType="Bit NOT NULL")]
		public bool IsAnimal
		{
			get
			{
				return this._IsAnimal;
			}
			set
			{
				if ((this._IsAnimal != value))
				{
					this.OnIsAnimalChanging(value);
					this.SendPropertyChanging();
					this._IsAnimal = value;
					this.SendPropertyChanged("IsAnimal");
					this.OnIsAnimalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAlien", DbType="Bit NOT NULL")]
		public bool IsAlien
		{
			get
			{
				return this._IsAlien;
			}
			set
			{
				if ((this._IsAlien != value))
				{
					this.OnIsAlienChanging(value);
					this.SendPropertyChanging();
					this._IsAlien = value;
					this.SendPropertyChanged("IsAlien");
					this.OnIsAlienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsThing", DbType="Bit NOT NULL")]
		public bool IsThing
		{
			get
			{
				return this._IsThing;
			}
			set
			{
				if ((this._IsThing != value))
				{
					this.OnIsThingChanging(value);
					this.SendPropertyChanging();
					this._IsThing = value;
					this.SendPropertyChanged("IsThing");
					this.OnIsThingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasSuperPowers", DbType="Bit NOT NULL")]
		public bool HasSuperPowers
		{
			get
			{
				return this._HasSuperPowers;
			}
			set
			{
				if ((this._HasSuperPowers != value))
				{
					this.OnHasSuperPowersChanging(value);
					this.SendPropertyChanging();
					this._HasSuperPowers = value;
					this.SendPropertyChanged("HasSuperPowers");
					this.OnHasSuperPowersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasPants", DbType="Bit NOT NULL")]
		public bool HasPants
		{
			get
			{
				return this._HasPants;
			}
			set
			{
				if ((this._HasPants != value))
				{
					this.OnHasPantsChanging(value);
					this.SendPropertyChanging();
					this._HasPants = value;
					this.SendPropertyChanged("HasPants");
					this.OnHasPantsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasShirt", DbType="Bit NOT NULL")]
		public bool HasShirt
		{
			get
			{
				return this._HasShirt;
			}
			set
			{
				if ((this._HasShirt != value))
				{
					this.OnHasShirtChanging(value);
					this.SendPropertyChanging();
					this._HasShirt = value;
					this.SendPropertyChanged("HasShirt");
					this.OnHasShirtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasShoes", DbType="Bit NOT NULL")]
		public bool HasShoes
		{
			get
			{
				return this._HasShoes;
			}
			set
			{
				if ((this._HasShoes != value))
				{
					this.OnHasShoesChanging(value);
					this.SendPropertyChanging();
					this._HasShoes = value;
					this.SendPropertyChanged("HasShoes");
					this.OnHasShoesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasBoots", DbType="Bit NOT NULL")]
		public bool HasBoots
		{
			get
			{
				return this._HasBoots;
			}
			set
			{
				if ((this._HasBoots != value))
				{
					this.OnHasBootsChanging(value);
					this.SendPropertyChanging();
					this._HasBoots = value;
					this.SendPropertyChanged("HasBoots");
					this.OnHasBootsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasHat", DbType="Bit NOT NULL")]
		public bool HasHat
		{
			get
			{
				return this._HasHat;
			}
			set
			{
				if ((this._HasHat != value))
				{
					this.OnHasHatChanging(value);
					this.SendPropertyChanging();
					this._HasHat = value;
					this.SendPropertyChanged("HasHat");
					this.OnHasHatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasCape", DbType="Bit NOT NULL")]
		public bool HasCape
		{
			get
			{
				return this._HasCape;
			}
			set
			{
				if ((this._HasCape != value))
				{
					this.OnHasCapeChanging(value);
					this.SendPropertyChanging();
					this._HasCape = value;
					this.SendPropertyChanged("HasCape");
					this.OnHasCapeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasScarf", DbType="Bit NOT NULL")]
		public bool HasScarf
		{
			get
			{
				return this._HasScarf;
			}
			set
			{
				if ((this._HasScarf != value))
				{
					this.OnHasScarfChanging(value);
					this.SendPropertyChanging();
					this._HasScarf = value;
					this.SendPropertyChanged("HasScarf");
					this.OnHasScarfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasDyedHair", DbType="Bit NOT NULL")]
		public bool HasDyedHair
		{
			get
			{
				return this._HasDyedHair;
			}
			set
			{
				if ((this._HasDyedHair != value))
				{
					this.OnHasDyedHairChanging(value);
					this.SendPropertyChanging();
					this._HasDyedHair = value;
					this.SendPropertyChanged("HasDyedHair");
					this.OnHasDyedHairChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasFacialHair", DbType="Bit NOT NULL")]
		public bool HasFacialHair
		{
			get
			{
				return this._HasFacialHair;
			}
			set
			{
				if ((this._HasFacialHair != value))
				{
					this.OnHasFacialHairChanging(value);
					this.SendPropertyChanging();
					this._HasFacialHair = value;
					this.SendPropertyChanged("HasFacialHair");
					this.OnHasFacialHairChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CostumeQuestion")]
	public partial class CostumeQuestion
	{
		
		private string _Question;
		
		private string _Answered;
		
		private string _DataField;
		
		private short _SortOrder;
		
		public CostumeQuestion()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Question", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Question
		{
			get
			{
				return this._Question;
			}
			set
			{
				if ((this._Question != value))
				{
					this._Question = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Answered", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Answered
		{
			get
			{
				return this._Answered;
			}
			set
			{
				if ((this._Answered != value))
				{
					this._Answered = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataField", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DataField
		{
			get
			{
				return this._DataField;
			}
			set
			{
				if ((this._DataField != value))
				{
					this._DataField = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortOrder", DbType="SmallInt NOT NULL")]
		public short SortOrder
		{
			get
			{
				return this._SortOrder;
			}
			set
			{
				if ((this._SortOrder != value))
				{
					this._SortOrder = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
